name: Update Articles Daily

on:
  schedule:
    - cron: '0 0 * * *' # 每天新加坡时间8AM触发（UTC+8）
  workflow_dispatch: # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install OpenAI library
        run: pip install openai

      - name: Run update script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python update_articles.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "limutong"
          git config --global user.email "mutongli@gmail.com"
          git add articles.csv
          git commit -m "Auto-update articles.csv" || echo "No changes to commit"
          git pull --rebase
          git push
